// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: lastfetchedat.sql

package database

import (
	"context"
)

const lastFetchedAt = `-- name: LastFetchedAt :exec

ALTER TABLE feeds ADD last_fetched_at TIMESTAMP NULL
`

func (q *Queries) LastFetchedAt(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, lastFetchedAt)
	return err
}
