-- +goose Up

CREATE EXTENSION IF NOT EXISTS "pgcrypto";
CREATE TABLE feeds(
id  UUID UNIQUE PRIMARY KEY DEFAULT gen_random_uuid(),
created_at TIMESTAMP NOT NULL DEFAULT now(),
updated_at TIMESTAMP NOT NULL DEFAULT now(),
name VARCHAR(255) NOT NULL,
url VARCHAR(255) UNIQUE NOT NULL,
user_id UUID REFERENCES users(id) ON DELETE CASCADE
);

-- +goose Down
DROP TABLE feeds;




